name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [10.x]
    
    services:
      mysql:
          image: mysql:8.0

          ports:
            - 3306:3306
          
          env:
            MYSQL_ROOT_PASSWORD: Gwada97195
            MYSQL_DATABASE: company

          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: npm ci
    - run: npm test
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ecedevops-project" #Must be unique in Heroku
          heroku_email: "arnaud.coquerelle@gmail.com"