name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [10.x]
    
    services:
      mysql_application:
          image: mysql:8.0

          ports:
            - 3306:3306
          
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
          env:
            MYSQL_ROOT_PASSWORD: Gwada97195
            MYSQL_DATABASE: company

    
    steps:  
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run test in container
        run: mysql -h localhost --port 3306 -u root -ppassword 
