name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: company
          MYSQL_USER: root
          MYSQL_PASSWORD: Gwada97195
          MYSQL_ROOT_PASSWORD: Gwada97195
        ports:
          - 3306:3306
    
    strategy:
      matrix:
        node-versions: [10.x]
    
    steps:  
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test