name: Build and Deploy
env:
    MYSQL_USER: nono
    MYSQL_PASSWORD: Gwada97195
    MYSQL_DATABASE: company
    MYSQL_ROOT_PASSWORD: Gwada97195
    MYSQL_HOST: mysql_server


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql_server
        ports:
          - 3000:3000
        env:
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        options: >-
          --name=mysql
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    strategy:
      matrix:
        node-versions: [10.x]
    
    steps:  
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test