name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [10.x]
    
    services:
      mysql:
          image: mysql:8.0

          ports:
            - 3306:3306
          
          env:
            CI: true
            MYSQL_ROOT_PASSWORD: Gwada97195
            MYSQL_DATABASE: company

          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm test