name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: company
          MYSQL_USER: root
          MYSQL_PASSWORD: Gwada97195
          MYSQL_ROOT_PASSWORD: Gwada97195
    
    strategy:
      matrix:
        node-versions: [10.x]
    
    steps:
      - uses: actions/checkout@v1
      - name: Verify MySQL connection
        env:
          PORT: 3306
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done     
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test