name: Build and Deploy
env:
    MYSQL_USER: nono
    MYSQL_PASSWORD: Gwada97195
    MYSQL_DATABASE: company
    MYSQL_ROOT_PASSWORD: Gwada97195
    MYSQL_HOST: mysql_server


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3000:3000
        volumes:
          - ./docker/company-db.sql:/docker-entrypoint-initdb.d/testing-db.sql
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: company
          MYSQL_USER: nono
          MYSQL_PASSWORD: secret
        networks:
          - devops-project_default
    
    strategy:
      matrix:
        node-versions: [10.x]
    
    steps:  
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test